### ISSUE TITLE
Identify and overlapping geometries

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2262] opened 2016-10-12 13:47 UTC
Identify (feature tooltip) doesn't select all overlapping geometries.
Steps:

1. Go here: https://s.geo.admin.ch/6ee4705f72 --> 5080T and 5002T overlap 
2. Click on the overlapping area --> 5002T is selected

Expected result: both 5002T and 5080T 

Affected layers:
- ch.swisstopo.wk50-papierkarte-zusammensetzung.metadata
- ch.swisstopo.lk25-papierkarte-zusammensetzung.metadata
- ch.swisstopo.lk100-papierkarte-zusammensetzung.metadata
- ch.swisstopo.lk50-papierkarte-zusammensetzung.metadata
- ch.swisstopo.wk25-papierkarte-zusammensetzung.metadata
- ch.swisstopo.skitourenkarte-50.metadata
- ch.swisstopo.gsk-papierkarte.metadata
- ch.swisstopo.wkt33-papierkarte.metadata
- ch.swisstopo.lk200-papierkarte.metadata
- ch.swisstopo.bk200-papierkarte.metadata

 

ch.swisstopo.wk50-papierkarte-zusammensetzung.metadata

**Comment by loicgasser** [comment] 2016-10-12 17:10
This is by design, not a bug. https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/shop/ShopDirective.js#L116
We fix the limit to 1 per layer. 
This probably needs adaptation in geoadmin

**Comment by gjn** [comment] 2016-10-13 07:07
Yes, these are simply conflicting requirements.

How many per layer results should we allow? Remember, this should be a global setting, affecting all shop layers.

**Comment by p1d1d1** [comment] 2016-10-13 07:40
Affecting all shop layers... I'm not sure. The Shop directive as far as I can understand form the code deals with "digital products", meaning those layers in map.geo.admin.ch which have a "shop menu" in the tooltip. 
And here the selection is "restricted" to one feature just because all selection geometries (map sheets and administrative units) are adjacent, meaning @ a specific point you can just have 1 object per layer. 
But it could also be that there are overlapping features and in this case all features @ the point should be selected.

It seems to me that here we mix 2 functionalities:

1) Opening the tooltip
2) Selecting the "clipping geometries" to fill in the Shop menu

Case is that both functionalities are done via an "identify" request and I understand that you'd like to use just one "identify" request, but point 1) should be standard tooltip behavior, meaning if there are let's say two overlapping features --> both are selected and the Object Information windows contains info on both.

BTW: https://s.geo.admin.ch/6ee855cc71
Any chance to buy maps 117 or 116?

**Comment by gjn** [comment] 2016-10-13 07:49
Maybe instead of limiting the result to 1, we should just put the tolerance to 0. Might be best of both worlds. Could be tried in a PR.

**Comment by p1d1d1** [comment] 2016-10-13 08:04
Exactly.

**Comment by gjn** [comment] 2016-10-25 11:11
Will be fixed tomorrow.

**Closed by gjn** 2016-10-25 11:11 UTC
Labels: 1st prio, enhancement
