### ISSUE TITLE
Shift highlight geometry

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2263] opened 2016-10-12 14:32 UTC
1. Go here: https://s.geo.admin.ch/6ee4a7b35f
2. Click on a feature --> the highlight geometry is shifted

Affected browser: IE11

Affected layers:
- ch.swisstopo.pixelkarte-pk25.metadata
- ch.swisstopo.pixelkarte-pk50.metadata
- ch.swisstopo.pixelkarte-pk200.metadata
- ch.swisstopo.pixelkarte-pk100.metadata

**Comment by loicgasser** [comment] 2016-10-12 17:29
Not browser specific. Wrong grids in the background

**Comment by loicgasser** [comment] 2016-10-12 17:34
I think the Wms source is shifted...

**Comment by AFoletti** [comment] 2016-10-13 03:43
I can't reproduce in any browser... @loicgasser did you already fix that?

**Comment by gjn** [comment] 2016-10-13 07:02
I can't reproduce. Can you attach a screenshot and the exact IE browsers version?

**Comment by p1d1d1** [comment] 2016-10-13 07:18
![image](https://cloud.githubusercontent.com/assets/1533649/19339833/10851d26-9126-11e6-91ea-2c049f6b9ca8.png)

**Comment by gjn** [comment] 2016-10-13 07:26
Strange:

![image](https://cloud.githubusercontent.com/assets/2572317/19340029/22e97d76-9127-11e6-8edf-badb807cd217.png)

Maybe caching issue of your browser?

**Comment by AFoletti** [comment] 2016-10-13 07:29
in @p1d1d1' image the highlight looks right (same and @gjn ) while the WMS image looks slightly shifted. I think we had someting similar with the zoom settings in the browser. @p1d1d1 could you check if you are using 100% zoom?

**Comment by loicgasser** [comment] 2016-10-13 07:40
I can reproduce on chrome on my phone 
![screenshot_20161013-093837](https://cloud.githubusercontent.com/assets/3306154/19340424/1d8e8a2c-9129-11e6-868e-2eb0a5846cfc.png)

**Comment by AFoletti** [comment] 2016-10-13 07:42
wow, that's a very big shift

**Comment by gjn** [comment] 2016-10-13 07:53
Browser zoom might be it. I can reproduce when I have browser zoom != 100%.

To me, this is minor bug as it's been like this since a long time and we never had bad feedback.

@p1d1d1 Can you adapt the original bug description to include that it's browser zoom related?

**Comment by AFoletti** [comment] 2016-10-13 08:01
Tested on Chrome on my wife's smartphone (sony xperia E1). The more I zoom out, the more shift I get

On desktop I can't reproduce even with zoom != 100 (tested with chrome 53 and Edge)

**Comment by p1d1d1** [comment] 2016-10-13 08:03
@gjn for sure a minor, BTW I can reproduce at whatever zoom level.

**Comment by gjn** [comment] 2016-10-13 08:19
I elevate this, because it not only affects the selection. But it also affects actual data where source is wms. This is a not-go.

It was just reported today by Adrian Wicht from the field, that they have the same behaviour with lfp2 layer:
[Testlink](https://map.geo.admin.ch/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.int.bgdi.ch%2FTRtXq7IeSr6ij12tmvgZ4A,ch.swisstopo.fixpunkte-lfp2&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=176169.22&Y=519613.58&zoom=10)

The point 12022110 should always be in swiss territory, but goes to france when client zoom is active.

@oterral Can you have a look?

**Comment by AFoletti** [comment] 2016-10-13 08:41
As ifo: the issues does not look to affect layers coming from the WMS-import tool

Steps to reproduce:
- open https://s.geo.admin.ch/6ee88e116d with zoom == 100% on your browser
- set zoom !=100
- reload. Surprise!

**Comment by ltclm** [comment] 2016-10-19 10:47
seems to be related to the devices dpi.
if i open this link on a macbook with retina display i can confirm the offset, if i open it on my office laptop, there is no offset.

https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissimage-product,ch.swisstopo.images-swissimage.metadata&X=265067.45&Y=652296.05&zoom=4

**Comment by oterral** [comment] 2016-10-19 12:12
@ltclm is right probably a pixel ratio issue. I can reproduce on the mac

**Comment by gjn** [comment] 2016-10-19 12:14
WMS requests are affected. Maybe wms request is not constructed correctly. Not sure if singleTile WMS is also affected or only tiled WMS.

**Comment by loicgasser** [comment] 2016-10-19 12:27
can you reproduce with pure ol3?

**Comment by oterral** [comment] 2016-10-19 12:34
Not with master http://openlayers.org/en/master/examples/wms-custom-proj.html

**Comment by oterral** [comment] 2016-10-19 12:44
It seems it's the gutter property which is responsible.

**Comment by loicgasser** [comment] 2016-10-19 12:53
yes can't reproduce with single tile.
[Single tile](https://tool-wms.dev.bgdi.ch/viewer?wmsUrl=%2F%2Fwms-bod.dev.bgdi.ch&layerId=ch.swisstopo.pixelkarte-pk25.metadata&lang=de&format=image%2Fpng&time=)

**Comment by oterral** [comment] 2016-10-20 06:48
Issue in ol #6001

**Comment by oterral** [comment] 2016-10-20 10:53
Fix ready https://github.com/openlayers/ol3/pull/6002

**Comment by gjn** [comment] 2016-10-20 11:01
Just discussed with Fred, will be in next ol3 release.

**Comment by oterral** [comment] 2016-10-20 11:26
@gjn do you want I deploy an emergency fix with the trick fedj told me in  openlayers/ol3#6001.

`serverType: 'mapserver' `

**Comment by gjn** [comment] 2016-10-20 11:31
No. It's been like this since quite some time, affects WMS layers only and only on certain browsers.

I think we can wait for next ol3 release and update.

**Comment by oterral** [comment] 2016-10-20 11:34
ok

**Comment by gjn** [comment] 2016-10-26 13:56
This is fixed on prod now.

**Closed by gjn** 2016-10-26 13:56 UTC
Labels: 2nd prio, bug
