### ISSUE TITLE
WMS GetFeatureInfo tooltip for eMapis

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2209] opened 2016-08-22 14:57 UTC
Most of eMapis use cases make use of WMS Import, e.g:

https://mf-geoadmin3.int.bgdi.ch/?topic=ech&layers=WMS%7C%7CHochbau%20(Query)%7C%7Chttps:%2F%2Fwms-bgdi.int.bgdi.ch%2F%3Fequery%3D(typ_code%3D41)%7C%7Cch.blw.emapis-hochbau&lang=de&bgLayer=voidLayer&X=184600.00&Y=622300.00&zoom=4

map.geo.admin.ch gives now the possibility to have a tooltip (based on GetFeatureInfo) on such layers.
Overall the output is not so user-friendly: it is not styled.

For the eMapis project we need this tooltip to behave as the standard tooltip (e.g. https://mf-chsdi3.int.bgdi.ch/shorten/6dde192aa6 --> click on the yellow object). 

Meaning:
- the same attributes of the standard tooltip should be enabled as output of a WMS GetFeatureInfo request 
- the tooltip on the WMS layers should contain (i) Layer Title (ii) the same attributes as the standard tooltip

**Comment by p1d1d1** [comment] 2016-09-10 08:38
Any news on this?

**Comment by ltclm** [comment] 2016-09-14 18:49
within map.geo.admin.ch we only have text/plain as getfeatureinfo format. You have to ask @oterral if we can support other formats.

it would look like this:
https://wms-bgdi.dev.bgdi.ch/ltclm/xx/?equery=(typ_code=41)&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=ch.blw.emapis-hochbau&LAYERS=ch.blw.emapis-hochbau&INFO_FORMAT=text/plain&I=50&J=50&CRS=EPSG%3A21781&STYLES=&WIDTH=101&HEIGHT=101&BBOX=608400%2C163775.00000000003%2C613450%2C168825.00000000003

But actually the emapis wms layer do not support getfeatureinfo. to enable getfeatureinfo we have to now which attributes we have to publish and we need the tranlsation of these attributes.

**Comment by ltclm** [comment] 2016-09-15 10:11
wms-bgdi has been configured. you can test the translated tooltips of the query layer [here](https://mf-geoadmin3.int.bgdi.ch/?topic=emapis&layers=WMS%7C%7CHochbau%20(Query)%7C%7Chttps:%2F%2Fwms-bgdi.dev.bgdi.ch%2Fltclm%2Fde%2F%3Fequery%3D(typ_code%3D41)%7C%7Cch.blw.emapis-hochbau,ch.blw.emapis-hochbau&lang=de&bgLayer=voidLayer&X=237412.37&Y=575609.28&zoom=4&catalogNodes=1916)


wms-bgdi pr: https://github.com/geoadmin/wms-bgdi/pull/94
mapfile_include pr: https://github.com/geoadmin/wms-mapfile_include/pull/54

**Comment by p1d1d1** [comment] 2016-09-15 11:31
Marcel thanks. And also language dependent!
By the way for the tests with BLW we need the GetFeatureInfo request enabled in wms-bgdi.int.bgdi.ch

**Comment by ltclm** [comment] 2016-09-15 12:13
translated emapis tooltips within wms-bgdi have been deployed to int, @daguer you're changes on emapis-zusammenfassung are on int too now.

note: the mf-geoadmin3 language selector has no impact on the getfeatureinfo language.

**Comment by p1d1d1** [comment] 2016-09-20 16:57
@ltclm would it be possible to enable a further attribute in the GetFeatureInfo for the emapis layers?

DE: Massnahme = column kurzbez_de in the postgis table
FR: Measure = column kurzbez_fr in the postgis table
IT: Provvedimento = column kurzbez_it in the postgis table

**Comment by ltclm** [comment] 2016-09-20 18:35
done and merged:
https://github.com/geoadmin/wms-bgdi/pull/96
please wms-bgdi related issues in this project.

**Comment by p1d1d1** [comment] 2016-09-22 14:17
@oterral Thanks to @ltclm we have "language enabled" WMS GetFeatureInfo.
But on map.geo.admin.ch it seems to me that the request doesn't use the language as set by the user.

**Comment by loicgasser** [comment] 2016-09-22 15:35
Do you have a testlink with the layer that doesn t work on int ?

**Comment by p1d1d1** [comment] 2016-09-22 16:10
Here the link:
https://mf-chsdi3.int.bgdi.ch/shorten/6e7e00eabf

The GetFeatureInfo support lang, e.g.:
DE: https://goo.gl/TMDqqi
FR: https://goo.gl/iDoWR6

But in mf_geoadmin3 the request is sent without lang parameter

**Comment by p1d1d1** [comment] 2016-09-22 16:19
One more issue. The "object Information" window of a tooltip on a WMS layer (WMS Import) is not so nice: scoll bars and the link "profil erstellen".
Could we get rid of both?thanks 

![screenshot_2016-09-22_18-16-43](https://cloud.githubusercontent.com/assets/1533649/18756576/c05d09c0-80f0-11e6-8e8c-5e9bc67d3266.png)

**Comment by loicgasser** [comment] 2016-09-23 07:44
yes the profile stuff will disapear with the next release I made a PR.

**Comment by loicgasser** [comment] 2016-09-23 07:58
Thank you for the link. The problem is that in the WMS getCap, you don't know what languages are avaible. Sure we can send the language we have in geoadmin, but we might end up with undesired side effects. We could also add an exception for in the WMS import for geoadmin WMS servers, but I don't like them.

How complex must the WMS queries be. We could use the badges in the layer tree (see zeitreihen layer) to select a type code. How many type code use cases do you have?
It would be easily extendable. (that's if they need filters)

![image](https://cloud.githubusercontent.com/assets/3306154/18778054/c0530204-8172-11e6-8bb7-41158f4e3ffd.png)

Also I have never seen such a bad symbology for low resolutions, how can you excpect people to even see there is something in the map? Can't you do anything about it, make the those bigger, a different color and so on?¨

Where is Charlie?
![image](https://cloud.githubusercontent.com/assets/3306154/18778320/0d64d5f8-8174-11e6-93be-d9aa88a794ca.png)

![image](https://cloud.githubusercontent.com/assets/3306154/18778335/20d2fdd6-8174-11e6-8d1d-e013a18c97cd.png)

![image](https://cloud.githubusercontent.com/assets/3306154/18778359/35fd8168-8174-11e6-98ef-a8dd41405d38.png)

**Comment by p1d1d1** [comment] 2016-09-23 08:37
@loicgasser let me try to address your points:

- GetFeatureInfo: no exception needed and I see no risks. Let's say a WMS Server supports the parameter "lang" but a specific language is not supported --> Server will answer with default.
Supported language: http://tinyurl.com/zdz3z32
Unsupported language: http://tinyurl.com/jb9ngzb
Case lang not supported --> the WMS Server will just ignore it and default will be returned.
So no risk to make language aware requests.

- Query: each layer can be filtered with 3 parameters and these can be combined via AND/OR. This was discussed last year but was not accepted because it needs new permalink parameters.

- Symbology: been implemented as defined in the model documentation, where the symbol definition is made for a scale 1:5000

**Comment by loicgasser** [comment] 2016-09-23 08:40
GetFeatureInfo: no exception needed and I see no risks. Let's say a WMS Server supports the parameter "lang" but a specific language is not supported --> Server will answer with default.
Supported language: http://tinyurl.com/zdz3z32
Unsupported language: http://tinyurl.com/jb9ngzb
Case lang not supported --> the WMS Server will just ignore it and default will be returned.
So no risk to make language aware requests.

Yes in theory.

Symbology: been implemented as defined in the model documentation, where the symbol definition is made for a scale 1:5000

sure it doesn't mean it's a good one.

**Comment by loicgasser** [comment] 2016-09-23 08:59
Profile link on WMS info tooltip fixed in https://github.com/geoadmin/mf-geoadmin3/pull/3502

**Comment by p1d1d1** [comment] 2016-10-14 09:06
@gjn @oterral got the following from customer:

![image](https://cloud.githubusercontent.com/assets/1533649/19381904/1197ebf2-91fe-11e6-808c-f89cc577c47e.png)

Any chance to get rid of this at least for our services?

**Comment by p1d1d1** [comment] 2016-10-14 09:32
@ltclm couldn't we apply a template in the mapfile for this?

**Comment by p1d1d1** [comment] 2016-10-14 10:20
@gjn @oterral @ltclm @loicgasser 
Guys please put this in stand-by. I maybe found a way to use the standard tooltip with WMS layers and equery.

**Closed** 2017-07-06 08:15 UTC
