### ISSUE TITLE
Error 500: SearchServer

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1481] opened 2015-05-28 15:27 UTC
http://api3.geo.admin.ch/rest/services/api/SearchServer?lang=de&type=locations&searchText=Le%20Ch%E2b&

**Comment by procrastinatio** [comment] 2015-05-28 15:52
subscriber...

**Comment by gjn** [comment] 2015-08-20 05:31
Duplicate of https://github.com/geoadmin/mf-chsdi3/issues/1601

**Closed by gjn** 2015-08-20 05:31 UTC
Labels: 2nd prio
