### ISSUE TITLE
Ascent and descent differences in profiles

### ISSUE THREAD

**Issue by daguer** [geoadmin/mf-chsdi3#3174] opened 2019-04-29 07:58 UTC
If we cut a line in several segments and that we calculate the sum of the ascents and descents, we do not obtain the same results as if we have only one segment.

**Comment by daguer** [comment] 2019-04-29 08:01
Hello @danduk82 , I don't know if the problem is known. It has been reported from helpdesk.

**Comment by davidoesch** [comment] 2019-04-29 08:32
duplicate of #4305

**Closed by davidoesch** 2019-04-29 08:32 UTC
Labels: bug
