### ISSUE TITLE
imageDisplay and tolerance in identify

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#3348] opened 2019-12-18 09:44 UTC
See https://jira.swisstopo.ch/browse/BGDIINF_SB-944

**Comment by rebert** [comment] 2019-12-18 10:13
https://github.com/geoadmin/mf-chsdi3/pull/3349

**Comment by ltkum** [comment] 2020-01-27 09:45
The issue is closed in Jira and the PR solving it has been merged. I close the Issue here too

**Closed by ltkum** 2020-01-27 09:45 UTC
