### ISSUE TITLE
increase result weight for exact matches in swissearch

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2925] opened 2018-06-14 06:48 UTC
We have to improve the way the results are ranked.
Until now, searching for "rotten" has generated the following sphinxquery:
```
@detail "rotten" | @detail "^rotten" | @detail "rotten$" | @detail "^rotten$" | @detail "rotten"~5 | @detail "rotten*" | @detail "^rotten*" | @detail "rotten*"~5 | @detail "*rotten*" | @detail "^*rotten*" | @detail "*rotten*"~5
``` 
If nothing has been found, we have repeated the same query in the fuzzy index.

The ranking of the query results cannot priorize exact matches over prefix, infix or suffix matches.

That's why we should try to split the query into two queries:
```bash
# first query higher ranking / relevance exact match:
@detail "rotten" | @detail "^rotten" | @detail "rotten$" | @detail "^rotten$" | @detail "rotten"~5

# second query lower ranking / relevance infix, prefix, suffix:
@detail "rotten*" | @detail "^rotten*" | @detail "rotten*"~5 | @detail "*rotten*" | @detail "^*rotten*" | @detail "*rotten*"~5
```
If nothing could be found with these two queries, we do a fuzzy search (as we already to it today).

p.e. search for "rotten"
exact match results are on position 12 and 13 of origin gazetteer, they should be on position 1 and 2

**Comment by davidoesch** [comment] 2018-11-05 09:38
Duplicate of #2946

**Closed by davidoesch** 2018-11-05 09:38 UTC
Labels: enhancement, question
