### ISSUE TITLE
Profile.json issue

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1599] opened 2015-08-12 09:48 UTC
503 error code on 2015-08-12T09:29:56.000Z for http://api3.geo.admin.ch/rest/services/profile.json

The following error can be seen in Apache Error log:

[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61] (70008)Partial results are valid but processing is incomplete: mod_wsgi (pid=16403): Unable to get bucket brigade for request., referer: https://map.geo.admin.ch
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61] mod_wsgi (pid=7172): Exception occurred processing WSGI script '/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/parts/modwsgi/wsgi'.
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61] Traceback (most recent call last):
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 242, in __call__
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     response = self.invoke_subrequest(request, use_tweens=True)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     response = handle_request(request)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     response = handler(request)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 99, in tm_tween
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     reraise(*exc_info)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 80, in tm_tween
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     response = handler(request)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 79, in handle_request
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     has_listeners and notify(NewRequest(request))
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/registry.py", line 74, in notify
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     [ _ for _ in self.subscribers(events, None) ]
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/zope.interface-4.0.5-py2.7-linux-x86_64.egg/zope/interface/registry.py", line 323, in subscribers
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     return self.adapters.subscribers(objects, provided)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/zope.interface-4.0.5-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 601, in subscribers
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     subscription(*objects)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/adapters.py", line 103, in derived_subscriber
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     return subscriber(arg[0])
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/subscribers.py", line 19, in add_localizer
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     request._LOCALE_ = helpers.locale_negotiator(request)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/lib/helpers.py", line 74, in locale_negotiator
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     lang = request.params.get('lang')
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/request.py", line 856, in params
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     params = NestedMultiDict(self.GET, self.POST)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/request.py", line 806, in POST
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     keep_blank_values=True)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/usr/lib/python2.7/cgi.py", line 506, in __init__
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     self.read_urlencoded()
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/usr/lib/python2.7/cgi.py", line 607, in read_urlencoded
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     qs = self.fp.read(self.length)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/request.py", line 1545, in readinto
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61]     data = self.file.read(sz0)
[Wed Aug 12 11:29:56 2015] [error] [client 10.220.6.61] IOError: request data read error

**Comment by cedricmoullet** [comment] 2015-08-12 09:49
@ltclm it seems to be an access disk error. On which disk are stored the DTM ?

**Comment by ltclm** [comment] 2015-08-13 19:58
Since this service is used with post request, it is not possible to reproduce the error from the information in the varnish logs. The following dashbord shows the requests on the profile service at that given time:
https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/api3%20profile%20%231599 
The client received a 503 error.

**Comment by ltclm** [comment] 2015-08-13 20:14
i have checked the index shape files with 
```bash
for file in $(find . -type f -name "*.shp" 2>/dev/null); do echo $file; ogrinfo -ro -al $file; done 1> /tmp/success 2> /tmp/error
```
and the raster dhm files with
```bash
for file in $(find . -type f -name "*.bt" 2>/dev/null); do echo $file; gdalinfo $file; done 1> /tmp/success 2> /tmp/error
```

None of these files is corrupt and www-data can access all of these files.

**Comment by gjn** [comment] 2015-08-18 06:20
Maybe we can extent logging on mf-chsdi3 level. In case the service returns a non 200, we could log the exact request to try to reproduce it later on. @loicgasser is this doable easily?

**Comment by loicgasser** [comment] 2015-08-18 18:23
It seems like all the errors appear in the local negotiator when the request parameters are parsed. (same for the search). I'll have to investigate.

**Comment by gjn** [comment] 2015-08-27 11:19
I think this [mod_wsgi](https://github.com/GrahamDumpleton/mod_wsgi/issues/58) issue might be the reason for the 503. There seems to be a time-out occuring while apache is passing the request data (json) to mod_wsgi.

We might update mod_wsgi to see how it's handled now. @danduk82 What version of mod_wsgi are we currently running on our infrastructure?

**Comment by gjn** [comment] 2015-08-27 11:41
I think the actual trigger of this might be an aborted profile request [1]. We do this sometimes when user draws quickly. In such a case, the upload of the json data stops, thus resulting in a read error in mod_wsgi, which isn't handled in our code and apache will issue a 503 in such cases. It's an assumption as of now as I was not able to reproduce this in dev.

I can try a patch that will catch the IOError and issue a 408 instead of the 503 unhandled error.

[1] https://groups.google.com/forum/#!topic/modwsgi/Qbe2SWCw4KY

**Comment by procrastinatio** [comment] 2015-09-08 10:54
We have:
```
apache2-mpm-prefork                          2.2.22-13+deb7u6
libapache2-mod-wsgi                          3.3-4+deb7u1                  
```

**Comment by cedricmoullet** [comment] 2015-09-16 09:15
We'll see after the deploy

**Comment by procrastinatio** [comment] 2015-10-05 19:49
According to the link from @gjn, this issue is fixed in *mod_wsgi 4.4.0*
In Debian Jessie we have *apache 2.4.0* and *mod_wsgi 4.3.0*, and we are stille using *wheezie*.

At least I have a test case that reproduce the error.

To solved it, we do not have many options, as profile/height is part of chsdi3. I would try another wsgi server, like gunicorn or uwsgi, and let run chsdi3 on mf0-prod with this settings, apache acting only as a proxy.

I feel using POST and _multipart_ has worsenen this problem.

**Comment by procrastinatio** [comment] 2015-10-05 21:48
The interesting fact is that you may crash all our services sending buggy POST requests!

**Comment by procrastinatio** [comment] 2015-10-06 08:59
So solutions so far:
* Upgrade to apache 2.4 and mod_wsgi 4.4+
* Use a different wsig server
* Filtering POST request with HAProxy

**Closed** 2015-11-25 10:09 UTC
Labels: 1st prio
