### ISSUE TITLE
Lk 1:10'000 in ch.swisstopo.pixelkarte-farbe group

### ISSUE THREAD

**Issue by ltbam** [geoadmin/mf-chsdi3#2125] opened 2016-06-07 12:25 UTC
Hi,

When I use the layer ch.swisstopo.pixelkarte-farbe from the WMTS interface, I've got all pixelkarte from 1:1'000'000 to 1:25'000, but the new 1:10'000 does not appear. Is it possible to have the 1:10'000 in the ch.swisstopo.pixelkarte-farbe layergroup?
@mariokeusen 

Thank you

**Comment by loicgasser** [comment] 2016-06-07 13:31
ping @AFoletti any idea?

**Comment by ltclm** [comment] 2016-06-08 06:45
this layer has been integrated as replacement for the tlm-karte-farbe which was not in this group too.

**Comment by loicgasser** [comment] 2016-06-08 07:48
Yes thks but I think it makes sense for it to be part of the group. Can we do that ?

**Comment by gjn** [comment] 2016-06-08 09:46
Duplicate of https://github.com/geoadmin/mf-chsdi3/issues/2114. It will get done.

**Closed by gjn** 2016-06-08 09:46 UTC
Labels: question
