### ISSUE TITLE
[location search] search for parcels is broken

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#3232] opened 2019-07-18 08:17 UTC
UC: search for e.g. "2258 Windisch" parcel
Result: map zooms/pans to the coordinate root point (0/0)
Expected: zoom/pam to correct parcel

Data provider told me that last week a small change was made and (successfully) tested.

Not sure, who can investigate that best from the people that currently are not on vacation.
Thanks @gjn for reassigning this.

**Comment by gjn** [comment] 2019-07-18 15:31
This is because of https://github.com/geoadmin/service-sphinxsearch/pull/403/files

The column `the_geom_point` is empty both in the original table and in the view. I think the idea was to have there a point that is inside the polygon (that's why the field was added). But somehow the columns is emptied. Maybe a rollback of the db?

@rebert @procrastinatio Can you please have a look at it?

1) If possible, create the 'the_geom_point` column and deploy the database
2) If 1 is not possible, revert the sphinx-search pull request  https://github.com/geoadmin/service-sphinxsearch/pull/403 and re-deploy sphinssearch (triggering update of search index)

As tomorrow is Friday, Monday is ok.

**Comment by gjn** [comment] 2019-07-18 15:37
There's another use case coming in that might have similar problems, even though it's not parcel related, but EGID related. This might be a data only problem:

```
Dear Webmaster,
today we have a strange response from your search service when try to looking for an egid. The service return correct information but y,x coordinates are empty.

For example:
https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=CH640702048838&type=locations&limit=10&origins=address,parcel,district&bbox=671500,73500,744800,161600

And the response is:
{"results":[{"id":108178301,"weight":2637,"attrs":{"origin":"parcel","geom_quadindex":"03210220322101","@geodist":6663272.5,"zoomlevel":10,"lon":0.0,"detail":"445 bellinzona 5002 ch640702048838","rank":10,"geom_st_box2d":"BOX(722185.848169866 124168.625126063,722218.078121648 124199.419543061)","lat":0.0,"num":445,"y":0.0,"x":0.0,"label":"<b>Bellinzona</b> 445 (CH 6407 0204 8838)"}}]}

Others searches seem to be ok.
```

**Comment by gjn** [comment] 2019-07-18 16:10
I'm not sure if the referenced PR of sphinx is deployed. It's merged but there is not release created in the sphimx repos. So please verify first.

If it's not deployed, then the cause for this issue is something else. If it's deployed, then a release note should be created.

**Comment by rebert** [comment] 2019-07-19 11:28
@ltclm thanks

**Closed by rebert** 2019-07-19 11:28 UTC
Labels: 1st prio, bug
