### ISSUE TITLE
Error 500 on identify

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1224] opened 2015-01-14 17:29 UTC
http://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=692124.830021982,220998.9882507511&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1600,1080,96&layers=all:ch.vbs.territorialregionen&mapExtent=681014.830021982,215908.9882507511,697014.830021982,226708.9882507511&tolerance=5

geometry issue ?

**Comment by cedricmoullet** [comment] 2015-01-14 17:30
One more: http://api3.geo.admin.ch/rest/services/ech/MapServer/identify?geometry=704206.7132676127,133316.31032245018&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1280,939,96&layers=all:ch.are.alpenkonvention&mapExtent=286906.7132676126,-19433.689677549875,1118906.7132676127,590916.3103224501&tolerance=5

**Comment by gjn** [comment] 2015-01-15 07:57
Seems like any identify for these layers is not working:
`ch.are.alpenkonvention`
`ch.vbs.territorialregionen`

[Link](http://map.geo.admin.ch/?X=159095.66&Y=834230.24&zoom=1&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.vbs.territorialregionen,ch.are.alpenkonvention&layers_opacity=0.6,0.75)

**Comment by loicgasser** [comment] 2015-01-15 08:45
I am on it.

**Comment by loicgasser** [comment] 2015-01-15 08:57
It crashed in shapely. Probably a geometry issue. @ltclm Can you check that the first and the last coordinates of the Polygons of these layers end with the same coordinate and if no, change it?

**Comment by loicgasser** [comment] 2015-01-15 09:02
or 3D geoms?

**Comment by ltclm** [comment] 2015-01-15 09:13
**ch.are.alpenkonvention -> 3d, valid**
```sql
psql -U www-data -h pg-0.dev.bgdi.ch -d are -c "select distinct st_ndims(the_geom),st_isvalidreason(the_geom) FROM siedlung_landschaft.alpenkonvention;"
 st_ndims | st_isvalidreason
----------+------------------
        3 | Valid Geometry
``` 

**ch.vbs.territorialregionen -> 3d, valid**
```sql
psql -U www-data -h pg-0.dev.bgdi.ch -d vbs -c "select distinct st_ndims(the_geom),st_isvalidreason(the_geom) FROM territorialregionen;"
 st_ndims | st_isvalidreason
----------+------------------
        3 | Valid Geometry
```

the whole list of tables with 3d geometries in ticket: https://github.com/geoadmin/mf-chsdi3/issues/1149

the tables have a st_valid constraint, so polygons with different start / end point cannot be created.

**Comment by loicgasser** [comment] 2015-01-15 09:28
```
st_ndims = 3
```

So it is a 3D geom which is not supported yet.

I think the problem will be with shapely when it comes down to it.

**Comment by gjn** [comment] 2015-01-15 09:31
Error is also the same with the merged sqlalchemy update branch.

**Comment by loicgasser** [comment] 2015-01-15 09:49
Yep it is really a shapely issue that cannot read 3D geoms.

**Comment by loicgasser** [comment] 2015-01-20 08:53
FYI same issue as https://github.com/geoadmin/mf-chsdi3/issues/1150

**Comment by cedricmoullet** [comment] 2015-01-29 12:27
@loicgasser what is the status of this ?

**Comment by loicgasser** [comment] 2015-01-29 13:06
Open PR waiting for review..
https://github.com/geoadmin/mf-chsdi3/pull/1210

**Comment by loicgasser** [comment] 2015-01-29 13:08
oh no my bad. 3D geoms stuff, we still do not support

**Comment by cedricmoullet** [comment] 2015-02-04 10:09
@loicgasser Could you please discuss with @elemoine and @fredj in order to see if it would be possible that shapely supports 3D geometry.

**Comment by loicgasser** [comment] 2015-02-13 10:32
shapely does support 3D geoms. The problem is not there but rather in the wkb we receive from postgres. I am sending an email now.

**Comment by ltclm** [comment] 2015-02-13 10:46
Have you tried to change the postgres output for binary, this can be done within the transaction
```sql
SET bytea_output TO 'hex'; -- valid values are hex escape
SELECT setting FROM pg_settings WHERE name = 'bytea_output';
```

**Comment by ltclm** [comment] 2015-02-13 12:40
hi loic
the following query is executed in the database by psycopg/sqlalchemy when clicking on a feature:

```sql
SELECT siedlung_landschaft.alpenkonvention.row_id AS siedlung_landschaft_alpenkonvention_row_id, ST_AsBinary(siedlung_landschaft.alpenkonvention.the_geom) AS siedlung_landschaft_alpenkonvention_the_geom, siedlung_landschaft.alpenkonvention.flaeche_ha AS siedlung_landschaft_alpenkonvention_flaeche_ha, siedlung_landschaft.alpenkonvention.stand AS siedlung_landschaft_alpenkonvention_stand
        FROM siedlung_landschaft.alpenkonvention
        WHERE ST_DWITHIN(siedlung_landschaft.alpenkonvention.the_geom, ST_GeomFromWKB('\x0101000000ffffffff0f1f2241ffffffffefc90341'::bytea, 21781), 50.0)
         LIMIT 200
```
alpenkonvention is another layer with 3d geometry which is not working at the moment.
If you could try to change the bytea_output within the transaction and try both options...

**Comment by loicgasser** [comment] 2015-02-13 13:20
http://postgis.net/docs/ST_AsBinary.html

Yep that's it I think.

**Comment by loicgasser** [comment] 2015-02-13 13:25
It has been change with version 9 of postgres, but hex should be the default format.

**Comment by loicgasser** [comment] 2015-02-13 17:08
I tried:
```python
def set_bytea_format_on_connect(dbapi_con, con_record):
    c = dbapi_con.cursor()
    c.execute("SET bytea_output = \'hex\'")
    c.close()

sqlalchemy.event.listen(Pool, 'connect', set_bytea_format_on_connect)
````

In
/etc/postgresql/9.4/main/postgresql.conf

Can't we try to change bytea_output there? Just to give it a try at least...

**Comment by ltclm** [comment] 2015-02-13 19:25
Hi Loic
I have just changed the bytea output postgresql.conf to 

```sql
$ psql -c "SHOW ALL;" | grep byte
 bytea_output                        | hex                                      | Sets the output format for bytea.
```

could you please try.

**Comment by loicgasser** [comment] 2015-02-13 20:08
Sure!

**Comment by loicgasser** [comment] 2015-02-13 20:20
:((

Nop, still get the error. Hope I am hitting the correct instance.
Maybe you're right, sqlAlchemy does a Session level `SET bytea_output = 'escape'`
Or
It is not the problem... It would be sad. Let's try escape instead and call it a day until we get an answer from @fredj or @elemoine

**Comment by loicgasser** [comment] 2015-02-17 14:34
See http://lists.osgeo.org/pipermail/geos-devel/2013-December/006755.html

Apparently [1], geos can only read/write EWKB encoded geometries, not WKB encoded geometries.
The problem is that geoalchemy2 reads the data as WKB (ST_AsBinary) but should use EWKB (ST_AsEWKB)

See also http://postgis.net/docs/using_postgis_dbmanagement.html#EWKB_EWKT:
"OGC formats only support 2d geometries, [...]" !

**Closed** 2015-02-20 15:47 UTC
Labels: bug prio 1
