### ISSUE TITLE
[extended tooltip] empty map window

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#2089] opened 2016-05-25 05:58 UTC
UC: open app, chose a layer with a map in the ext tooltip (e.g. those from the permalink below) click an object, open the extended tooltip, watch the map window
Result: no map visible (blank)
Expected: map is visible as designed for each extended tooltip

This is a prio1 imho! thanks for taking care accordingly

**Comment by mariokeusen** [comment] 2016-05-25 05:59
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&X=164500.00&Y=626970.00&zoom=3&layers=ch.bafu.wasser-teileinzugsgebiete_2,ch.bazl.luftfahrthindernis&layers_opacity=0.75,1

**Comment by AFoletti** [comment] 2016-05-25 06:06
does not work on DEV either, but I get no error message
I tested it outside the Bundesnetz too, and the problem is still there

I'll look further into it

**Comment by AFoletti** [comment] 2016-05-25 06:13
ok, found the issue

var map = new ga.Map --> ga is not defined

I have no idea why this should not work anymore. Trying a git bisect :stuck_out_tongue_closed_eyes:

**Comment by gjn** [comment] 2016-05-25 06:31
Introduced with https://github.com/geoadmin/mf-chsdi3/pull/1980/files

Deployed on April 27th.

@AFoletti is taking care of it. Should be fixed after today's deploy.

**Comment by AFoletti** [comment] 2016-05-25 06:59
fixed in the referenced PR

I checked every single extended tooltip and each one looks "fine" to me.
"Fine" because every extended tooltip works, but we sould maybe took half a day to improve the layout of some of them :)

**Closed** 2016-05-25 07:14 UTC
Labels: 1st prio
