### ISSUE TITLE
The wkid field of geometries returned by the Find service is random 🤡

### ISSUE THREAD

**Issue by RobertoMinelli** [geoadmin/mf-chsdi3#2965] opened 2018-07-26 07:57 UTC
Dear all, 

@andreamocci and I discovered another interesting bug in the [Find API](https://api3.geo.admin.ch/services/sdiservices.html#find) which is somehow related to #2910.

We can reproduce the problem in the layer `ch.bfe.solarenergie-eignung-fassaden`, but it might be present also in other layers.

If you perform a find request on this layer **specifying** `sr=2056`, the returned geometries are indeed in `LV95 (2056)` but the `spatialReference` field in the response is random. Sometimes it is correct (i.e., `"wkid": 2056`) and sometimes is wrong  (i.e., `"wkid": 21781`).

[Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?layer=ch.bfe.solarenergie-eignung-fassaden&searchText=1288122&searchField=building_id&returnGeometry=true&contains=false&sr=2056) you can find a sample request. Try to execute it a few times and observe the change in the `wkid` of the results.

Cheers,
Rob

cc: @procrastinatio

**Comment by RobertoMinelli** [comment] 2018-07-26 08:03
Hereby I confirm that the bug is reproducible also in the `ch.bfe.solarenergie-eignung-daecher` layer. 

[Here](https://api3.geo.admin.ch/rest/services/api/MapServer/find?layer=ch.bfe.solarenergie-eignung-daecher&searchText=1288122&searchField=building_id&returnGeometry=true&contains=false&sr=2056) you can find a sample find request for the `ch.bfe.solarenergie-eignung-daecher` layer. Please, try to execute it a few times and observe the random changes to the `wkid` field in the responses.

Cheers,
Rob

**Comment by ltkum** [comment] 2018-09-18 13:19
Problem loosely identified : the default value for the srid value (assuming there is no spatial Reference given) is 21781. Which means that, for some reason, sometimes, he doesn't take the sr parameter into account and simply take the default value into account.

I'll begin investigating why it doesn't take a given parameters into account and try to correct this.

**Comment by ltkum** [comment] 2018-10-09 17:40
Been trying the exact same query on a "personal" deploy ( "http://mf-chsdi3.dev.bgdi.ch/ltkum/rest/services/api/MapServer/find?layer=ch.bfe.solarenergie-eignung-daecher&searchText=1288122&searchField=building_id&returnGeometry=true&contains=false&sr=2056" ), using a curl loop. 

the following script was used. It takes only the wkid from the resulting json.
``` bash
# !/bin/bash

for e in {{1..1000}}; do
echo "$e"
curl "http://mf-chsdi3.dev.bgdi.ch/ltkum/rest/services/api/MapServer/find?layer=ch.bfe.solarenergie-eignung-daecher&searchText=1288122&searchField=building_id&returnGeometry=true&contains=false&sr=2056" | jq '.results' | jq '.[]' | jq '.geometry' | jq '.spatialReference' | jq '.wkid'
done
```
I grepped 21781 from the log file generated and I found... no match at all.

which seems to indicate that the problem lies on the production environment. 

Request header : 
```
**Host: mf-chsdi3.dev.bgdi.ch**
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
**Accept-Encoding: gzip, deflate**

Connection: keep-alive
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache
```
The blank line is **Referer: https://github.com/geoadmin/mf-chsdi3/issues/2965** on the production environment. All differences are in bold characters

Answer Header:
```
HTTP/**1.1** 200 OK
**D**ate: Tue, 09 Oct 2018 **17:27:55** GMT
**C**ontent-Type: application/json
**C**ontent-Length: 1731
**Connection: keep-alive**
**S**erver: Apache/2.4.10 (Debian)
**A**ccess-**C**ontrol-**A**llow-**O**rigin: *
**A**ccess-**C**ontrol-**A**llow-**M**ethods: POST, GET, OPTIONS
**A**ccess-**C**ontrol-**A**llow-**H**eaders: x-requested-with, Content-Type, origin, authorization, accept, client-security-token
**V**ary: Accept-Encoding
**C**ontent-**E**ncoding: gzip
**X-UA-C**ompatible: IE=Edge
**Cache-Control: no-cache**
**X-Varnish: 112896906**
**A**ge: 0
**V**ia: 1.1 varnish-v4
**X**-Cache: MISS
**A**ccept-**R**anges: bytes

```
The blank line contains, in api3, **X-Firefox-Spdy: h2**
The line 4 is absent from the api3.geoadmin endpoint, and we're obviously in http 1.1 in my case while being in http2.0 in production. 

Can someone tell me what the difference between the production server and my branch (i only pulled master, created a branch and used make user) are on the infrastructure level ?

**Comment by ltkum** [comment] 2018-10-10 11:56
Curl doesn't encounter the problem at all even on the prod branch, with or without cache.

Seems to me like the problem only happens in browsers. I currently tested with Firefox, and I'll try with other browsers to see if the problem is reproductible on those too.

**Comment by ltkum** [comment] 2018-10-12 07:41
If you make the request specifying srid=21771, 
https://api3.geo.admin.ch/rest/services/api/MapServer/find?layer=ch.bfe.solarenergie-eignung-daecher&searchText=1288122&searchField=building_id&returnGeometry=true&contains=false&sr=21781
it sometimes returns a wkid of 2056 too. I first thought it was a "reset to default value problem", but seems the problem lies elsewhere

**Comment by procrastinatio** [comment] 2019-06-05 13:46
@RobertoMinelli I think we fixed it. It was related to requests setting the output `srid` in the data model, which is not a good idea as the models are global.

**Comment by procrastinatio** [comment] 2019-10-23 09:35
OK. Closing

**Closed by procrastinatio** 2019-10-23 09:35 UTC
Labels: 2nd prio
