### ISSUE TITLE
SHOP: bug  1:25'000 Swiss Map Raster

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2618] opened 2017-07-31 07:22 UTC
1) Click on this point: https://s.geo.admin.ch/74c2d8d7ea 
2) Map 2200 is selected twice. This is wrong

Expected: Map 2200 AND 1179 are selected.

**Comment by p1d1d1** [comment] 2017-07-31 07:25
Same issue with maps: 1353 and 1374

**Comment by p1d1d1** [comment] 2017-07-31 08:29
Same 1275 and 1294, i guess there are more.

**Comment by mariokeusen** [comment] 2017-07-31 13:01
Could not reproduce:
![shop_smr25](https://user-images.githubusercontent.com/4577749/28778782-0f381c00-7601-11e7-8317-64846ed69dec.PNG)

**Comment by p1d1d1** [comment] 2017-07-31 14:57
sorry, my description was not complete. Make a mouse over on the 2 entries in the tooltip. same geometry is highlighted

**Comment by mariokeusen** [comment] 2017-08-02 09:16
Ah, now I see. 

- There's something wrongly linked with the geometries: when I want to order by sheet from the Samnaum tooltip, the dropdown for Piz Lad appears. Should be Samnaun
- Second strange behaviour is that by clicking on the point only the 2200 Piz Lad geometry is highlighted, but not the 1179 Samnaun. This is an area where I would expect both sheet geometries highlighted. Does this have any shop-specific reason or is this simply a bug, @pauloamado ?

Problem concerns only the cases mentioned above by @p1d1d1 plus this case here on the LK100: https://s.geo.admin.ch/74cd937a44. These are the only cases, where we have overlapping map sheet polygons on the digital raster nationalmap metalayers.

**Comment by gjn** [comment] 2017-08-03 06:30
@ltclm Could you have a look? Looks like a data issue to me.

**Comment by ltclm** [comment] 2017-08-03 06:57
the following sheets have overlapping geometry:
1170 + 2200
1275 + 1294
1353 + 1374

We will have to modifiy the footprint geometry, im waiting for feedback / decision of bovier.

**Comment by p1d1d1** [comment] 2017-08-03 07:47
Isn't data owner Karto?

**Comment by mariokeusen** [comment] 2017-08-03 07:54
DO is Karto

**Comment by p1d1d1** [comment] 2017-08-03 08:01
Have a meeting with Karto on 04.09 about his issue. Asked Karto to have Topo in the loop.

**Comment by gjn** [comment] 2017-08-03 11:15
The highlight issue (and woring information in the tooltip) was a separate issue than the labeling. Here's a PR trying to address the tooltip and highlighting issue:

https://github.com/geoadmin/mf-geoadmin3/pull/3915

**Comment by gjn** [comment] 2017-08-16 11:30
Will be fixed front-end after today's deploy.

**Closed by gjn** 2017-08-16 11:30 UTC
