### ISSUE TITLE
translate drawing layer name in layer selector

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#1731] opened 2015-11-02 07:58 UTC
The name of the drawing layer is not translated in the layer selector:
![image](https://cloud.githubusercontent.com/assets/5286659/10876740/c9a0bda8-813f-11e5-95ff-151caad42407.png)

**Comment by davidoesch** [comment] 2015-11-02 08:06
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2811

**Closed by davidoesch** 2015-11-02 08:06 UTC
Labels: 3rd prio
