### ISSUE TITLE
Support abbrevation for addresses

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#2726] opened 2017-11-30 07:18 UTC
In Swisssearch, abbreviations like 
Seftigenstr.
Bundespl.
Av.
etc
Are not recognized anymore. ( I'm quite sure this worked in the past) 

Can you dig out the old behavior?

**Comment by ltclm** [comment] 2017-11-30 09:27
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/4036

**Closed** 2017-12-06 09:55 UTC
Labels: 2nd prio, bug
