### ISSUE TITLE
WMTS GetCap 2056 not working

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3405] opened 2020-03-04 07:13 UTC
Issue

"wir nutzen WMTS (https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml) in unserer Kartenapplikation. Seit heute Nachmittag (3.3.2020) funktioniert der Aufruf der WMTS-Capabilities für EPSG 2056 nicht mehr bzw. lädt endlos (mit EPSG 21781 funktioniert der WMTS-Capabilities-Aufruf). Wenn der Header «cache-control» mit dem Wert «no-cache» hinzugefügt wird, werden die WMTS-Capabilities empfangen. Dies ist für uns aktuell jedoch keine Lösung, da dies nicht einfach so in unsere Applikation eingebaut werden kann."

Similar issues has been reported for the same case by kanton Zug and Kanton Bern

the workaround " Header «cache-control» replaced«no-cache»" is not a long term solution

prio 1 sinde it affects core operative service of cantons

**Comment by davidoesch** [comment] 2020-03-04 07:15
"Was ich gestern Abend festgestellt habe ist, dass folgendes funktionierte:
https://wmts.geo.admin.ch/EPSG/21781/1.0.0/WMTSCapabilities.xml
https://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml (per default in 21781)
https://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.EPSG.2056.xml

allerdings nicht:
https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml
"

**Comment by boecklic** [comment] 2020-03-04 08:49
Currently we're experiencing the issue again. We're investigating and posting updates here as soon as we know more

**Comment by boecklic** [comment] 2020-03-04 12:34
The issue was likely caused by an unusual high request rate on https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml . We've taken measures to mitigate the effects, https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml should work normally again. I'm therefore closing this issue. Pls reopen if issue occurs again.

**Closed by boecklic** 2020-03-04 12:34 UTC
Labels: 1st prio, bug

**Comment by danduk82** [comment] 2020-03-04 14:21
@boecklic , I would really suggest to use a cache at varnish level of say, 30 seconds, on the capabilities. Moreover, there seems to be something strange is the cache headers because the header `max-age` is repeated, and once it says `0`, and once `1800`:

```bash
curl -I https://wmts.geo.admin.ch/EPSG/2056/1.0.0
[...]
cache-control: max-age=0, must-revalidate, no-cache, no-store, max-age=1800, public
[...]
```
thanks for solving the issue. :)
